In [52]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [113]:
X_test= pd.read_csv("X_test.csv",header= None)
X = pd.read_csv("X_train.csv",header= None)
y_test=pd.read_csv("y_test.csv",header=None)
y=pd.read_csv("y_train.csv",header=None)

XT = np.transpose(X)
XTX = np.dot(XT,X)
XTy= np.dot(XT,y)
I=np.identity(7)

In [159]:
def ridgeregression(lamda):

    return np.dot(np.linalg.inv(np.dot(lamda,I) + XTX),XTy)

wrr=np.empty([0,7])

for x in range(1,5000):
    wrr = np.vstack([wrr, np.transpose(ridgeregression(x))])

In [160]:
wrr

array([[-0.44572373,  0.57776701, -0.34449687, ...,  0.25110636,
         2.76333513,  0.00812705],
       [-0.44130977,  0.44574021, -0.39917848, ...,  0.21690527,
         2.74640485,  0.00636261],
       [-0.44142786,  0.33021663, -0.44919973, ...,  0.18637078,
         2.73044869,  0.0048159 ],
       ..., 
       [-0.32581703, -0.33557558, -0.32390749, ...,  0.16123684,
         0.25667615,  0.00806463],
       [-0.32576685, -0.33552376, -0.3238576 , ...,  0.16121416,
         0.25663292,  0.00806358],
       [-0.32571669, -0.33547195, -0.32380772, ...,  0.16119149,
         0.2565897 ,  0.00806252]])

In [139]:
c1=np.transpose(ridgeregression(1))
c2=np.transpose(ridgeregression(2))

In [143]:
np.append(wrr,c1,axis=0)

array([[-0.44572373,  0.57776701, -0.34449687, -5.40968597,  0.25110636,
         2.76333513,  0.00812705]])

In [153]:
wrr = np.vstack([wrr, c2])

In [154]:
wrr

array([[-0.44572373,  0.57776701, -0.34449687, -5.40968597,  0.25110636,
         2.76333513,  0.00812705],
       [-0.44130977,  0.44574021, -0.39917848, -5.25028919,  0.21690527,
         2.74640485,  0.00636261]])

In [116]:
c

array([[-0.44572373,  0.57776701, -0.34449687, -5.40968597,  0.25110636,
         2.76333513,  0.00812705]])